from pathlib import Path
from scholarly import scholarly
import yaml
import re

SCHOLAR_ID = "xqccd64AAAAJ"

OUT = Path("publications.md")
NOTES_FILE = Path("_data/publication_notes.yml")


def clean_text(value):
    if not value:
        return ""
    return str(value).replace("\n", " ").strip()


def slugify(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def load_notes():
    if NOTES_FILE.exists():
        with NOTES_FILE.open("r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    return {}


def make_link(label, url):
    if url:
        return f"[{label}]({url})"
    return ""


def main():
    notes = load_notes()

    author = scholarly.search_author_id(SCHOLAR_ID)
    author = scholarly.fill(author, sections=["publications"])

    publications = []

    for pub in author.get("publications", []):
        try:
            filled = scholarly.fill(pub)
            bib = filled.get("bib", {})

            title = clean_text(bib.get("title"))
            year = clean_text(bib.get("pub_year"))
            authors = clean_text(bib.get("author"))
            venue = clean_text(
                bib.get("journal")
                or bib.get("conference")
                or bib.get("venue")
                or bib.get("publisher")
            )

            url = clean_text(filled.get("pub_url") or bib.get("url"))

            publications.append({
                "title": title,
                "year": year,
                "authors": authors,
                "venue": venue,
                "url": url,
            })

        except Exception as e:
            print(f"Skipped one publication: {e}")

    publications.sort(
        key=lambda x: int(x["year"]) if str(x["year"]).isdigit() else 0,
        reverse=True
    )

    lines = [
        "---",
        "layout: page",
        "title: Publications",
        "permalink: /publications/",
        "---",
        "",
        "# Publications",
        "",
        "<!-- This file is automatically generated. -->",
        "<!-- Add custom notes in _data/publication_notes.yml, not here. -->",
        "",
    ]

    current_year = None

    for p in publications:
        title = p["title"]
        year = p["year"] or "Unknown year"

        if year != current_year:
            lines.append(f"## {year}")
            lines.append("")
            current_year = year

        extra = notes.get(title, {})

        paper_link = extra.get("paper") or p["url"]
        code_link = extra.get("code")
        slides_link = extra.get("slides")
        video_link = extra.get("video")
        note = extra.get("note")

        links = [
            make_link("Paper", paper_link),
            make_link("Code", code_link),
            make_link("Slides", slides_link),
            make_link("Video", video_link),
        ]
        links = [x for x in links if x]

        lines.append(f"### {title}")
        lines.append("")
        if p["authors"]:
            lines.append(f"**Authors:** {p['authors']}")
            lines.append("")
        if p["venue"]:
            lines.append(f"**Venue:** {p['venue']}")
            lines.append("")
        if links:
            lines.append(" | ".join links)
            lines.append("")
        if note:
            lines.append(f"**Note:** {note}")
            lines.append("")
        lines.append("---")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Updated {OUT} with {len(publications)} publications.")


if __name__ == "__main__":
    main()
